<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="GVDIACN-44" name="com.qa.wave3.FlexDeploy" tests="6" failures="1" timestamp="2020-08-19T21:07:45 IST" time="15.275" errors="0">
  <testcase name="FlexDeploy_S05_Web_Prod_UserLogin" time="15.275" classname="com.qa.wave3.FlexDeploy">
    <failure type="java.lang.AssertionError" message="FlexDeploy Home page is not displayed expected [FlexDeploy - Home] but found [FlexDeploy Login]">
      <![CDATA[java.lang.AssertionError: FlexDeploy Home page is not displayed expected [FlexDeploy - Home] but found [FlexDeploy Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.qa.wave3.FlexDeploy.TM_FlexDeploy_S05_Web_ProdUserLogin_ReleasesTab(FlexDeploy.java:315)
at com.qa.wave3.FlexDeploy.FlexDeploy_S05_Web_Prod_UserLogin(FlexDeploy.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- FlexDeploy_S05_Web_Prod_UserLogin -->
  <testcase name="FlexDeploy_S06_Web_Prod_" classname="com.qa.wave3.FlexDeploy">
    <skipped/>
  </testcase> <!-- FlexDeploy_S06_Web_Prod_ -->
  <testcase name="FlexDeploy_S02_Web_VAL_" classname="com.qa.wave3.FlexDeploy">
    <skipped/>
  </testcase> <!-- FlexDeploy_S02_Web_VAL_ -->
  <testcase name="FlexDeploy_S01_Web_Dev_UserLogin" classname="com.qa.wave3.FlexDeploy">
    <skipped/>
  </testcase> <!-- FlexDeploy_S01_Web_Dev_UserLogin -->
  <testcase name="FlexDeploy_S02_Web_Dev_" classname="com.qa.wave3.FlexDeploy">
    <skipped/>
  </testcase> <!-- FlexDeploy_S02_Web_Dev_ -->
  <testcase name="FlexDeploy_S03_Web_VAL_UserLogin" classname="com.qa.wave3.FlexDeploy">
    <skipped/>
  </testcase> <!-- FlexDeploy_S03_Web_VAL_UserLogin -->
</testsuite> <!-- com.qa.wave3.FlexDeploy -->
